### PR TITLE
use emoji-function

### PR DESCRIPTION
**Pull request by westnordost**
While I was browsing the code, I noticed that you manually maintain a list of country flag emojis. This is not necessary, they can be derived from the ISO 3166-1 alpha-2 code. See https://en.wikipedia.org/wiki/Regional_indicator_symbol

### CODE REVIEW

**Comment by vanniktech** [comment]
I like it, thanks! Could you extend the `country` test case to also include the flag?

**Comment by westnordost** [comment]
Hm? I didn't change the interface, so the tests should work as before.

**Comment by vanniktech** [comment]
Yes. The current tests are not checking for the emoji: https://github.com/vanniktech/multiplatform-locale/blob/03561cd84e1ff4a8a630a2b143ee7ef26b731e26/multiplatform-locale/src/commonTest/kotlin/com/vanniktech/locale/CountryTest.kt#L61

**Comment by westnordost** [comment]
Hm, I see, but then, basically, one still would have to maintain the flag emojis manually, but instead in the test code. So in the end, nothing is won. I'll rather close this PR in this case.

**Comment by vanniktech** [comment]
Yeah but it would be auto generated and isn't too bad. Don't worry I can get to it also.

**Pull request closed without merging**
